<a href="https://colab.research.google.com/github/Harish21b/sirpi/blob/main/Exe2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Variables and Data Types
Write a Python program that swaps two numbers without using a third variable.

In [ ]:
a=10
b=20
print("before swaapping",a,b)
a,b=b,a
print("after swapping",a,b)


x=30
y=40
x=x+y
y=x-y
x=x-y
print(x)
print(y)

before swaapping 10 20
after swapping 20 10
40
30


2. Lists - Nested Lists
You have a nested list:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
a) Extract and print the middle element from the nested list.
b) Flatten the list into a single list [1, 2, 3, 4, 5, 6, 7, 8, 9] without using loops.

In [ ]:
data =[[1, 2, 3],[4, 5, 6],[7, 8, 9]]
print(data[1][1])
print(data[0]+data[1]+data[2])

5
[1, 2, 3, 4, 5, 6, 7, 8, 9]


3. Tuples - Tuple Unpacking
Given:
values = (100, 200, 300)
a) Unpack this tuple into three variables and print them.
b) Swap the values without using a temporary variable.

In [ ]:
values=(100, 200, 300)
x=values[0]
y=values[1]
z=values[2]
print(x,y,z)
x,y,z=z,x,y
print(x,y,z)

100 200 300
300 100 200


4. Dictionary - Complex Keys
Create a dictionary where:
Keys are tuples representing (x, y) coordinates.
Values are the sum of x and y.
Example:
{ (1,2): 3, (3,4): 7, (5,6): 11 }
Write a function to retrieve the sum for a given coordinate.


In [ ]:
def dictaddition(x,y):
  dict2[x,y]=x+y
  dict3=dict2
  return dict3

dict3={}
dict2={}
s=[]
for i in range(0,5):
  j=int(input("enter x coordinate value "))
  h=int(input("enter y coordinate value "))
  o=[]
  o.append(j)
  o.append(h)
  s.append(tuple(o))
  #print(s)
a={}
for i in s:
  a=dictaddition(i[0],i[1])
print(a)

enter x coordinate value 1
enter y coordinate value 2
enter x coordinate value 3
enter y coordinate value 4
enter x coordinate value 5
enter y coordinate value 6
enter x coordinate value 7
enter y coordinate value 8
enter x coordinate value 9
enter y coordinate value 0
{(1, 2): 3, (3, 4): 7, (5, 6): 11, (7, 8): 15, (9, 0): 9}


5. Functions - Nested Functions
Write a function outer_function(a, b) that:
Contains an inner function to calculate a² + b².
Returns the result.
Call outer_function(3, 4) and print the result.


In [ ]:
def outer_fun(a,b):
  def inner_fun(a,b):
    c=(a*a)+(b*b)
    return c
  return inner_fun(a,b)


x=outer_fun(3,4)
print(x)



25


6. Functions - Lambda & Map
You are given a list:
numbers = [1, 2, 3, 4, 5]
Use a lambda function and map() to generate a list where each number is cubed.

In [ ]:
a=[1,2,3,4,5]
x=list(map(lambda q:q**3,a))
print("after cubing",x)


after cubing [1, 8, 27, 64, 125]


7. Functions - Recursion
Write a recursive function to calculate the sum of digits of a given number.
Example:
Input: 1234
Output: 10  (1+2+3+4)


In [ ]:
def digit_sum(x):
    sum=0
    if(x>9):
        sum=sum+(x%10)
        return sum+digit_sum(int(x/10))
    else:
        return x

a=int(input("enter a value :"))
print(digit_sum(a))

8. List Comprehensions
Generate a list of all numbers between 1 and 100 that:
Are divisible by 5
But not by 3
Use list comprehension.

In [ ]:
num=[i for i in range(1,100) if i%5==0 and i%3!=0]
print(num)

[5, 10, 20, 25, 35, 40, 50, 55, 65, 70, 80, 85, 95]


In [ ]:
num=[i**3 for i in range(1,10)]
print(num)

[1, 8, 27, 64, 125, 216, 343, 512, 729]


In [ ]:
val= True  if (11%2==0) else False
print(val)

False


9. Dictionary - Sorting by Values
Given:
scores = {"Alice": 90, "Bob": 85, "Eve": 92}
Sort this dictionary by values in descending order and print the result.

In [ ]:
scores={"Alice":90,"Bob":85,"Eve":92}
b=dict(sorted(scores.items(),key=lambda i:i[1],reverse=True))
print(b)

{'Eve': 92, 'Alice': 90, 'Bob': 85}


In [ ]:
di={"alice":90,"bob":85,"eve":92,"baba":100}
sorted_dict=dict(sorted(di.items(),key=lambda i:i[0],reverse=True))
print(sorted_dict)

{'eve': 92, 'bob': 85, 'baba': 100, 'alice': 90}


10. Sets - Unique Characters
Write a Python function that takes a string as input and returns:
A set of unique characters in the string.
The number of unique characters.
Example:
Input: "hello"
Output: {'h', 'e', 'l', 'o'}, 4


In [ ]:
def unique(a):
  c=set(a)
  d=len(c)
  return c,d
b="hello"
unique_val,len_unique_val=(unique(b))
print(unique_val,len_unique_val)

{'e', 'l', 'o', 'h'} 4


11. Tuples - Finding Common Elements
Given two tuples:
t1 = (1, 2, 3, 4, 5)
t2 = (4, 5, 6, 7, 8)
Find and print the common elements.

In [ ]:
t1=set((1, 2, 3, 4, 5))
t2=set((4, 5, 6, 7, 8))
t1.intersection(t2)

{4, 5}

12. Dictionary - Reverse Key-Value Mapping
Given a dictionary:
data = {"A": 1, "B": 2, "C": 3}
Write a program to swap keys and values:
Output: {1: "A", 2: "B", 3: "C"}


In [ ]:
data = {"A": 1, "B": 2, "C": 3}
reversed_data = {value: key for key,value in data.items()}
print(reversed_data)  # Output: {1: 'A', 2: 'B', 3: 'C'}

{1: 'A', 2: 'B', 3: 'C'}


13. Functions - Multiple Return Values
Write a function that takes two numbers as input and returns:
Their sum
Their difference
Their product
Their quotient
Print all four results.


In [ ]:
def calc(a,b):
  c=a+b
  d=a-b
  e=a*b
  f=a/b
  return c,d,e,f

x,y,z,o=calc(10,2)
print(x,y,z,o)


12 8 20 5.0


14. List - Finding Second Largest Number
Write a function to find the second largest number in a given list without using sort().
Example:
Input: [10, 20, 4, 45, 99]
Output: 45


In [ ]:
a=[77,10,20,4,45,99,66,33]
max_h=a[0]
max_s=a[0]
for i in range(0,(len(a))):
  if (a[i]>max_h):
    max_h=a[i]
  if(a[i]>max_s and a[i]!=max_h):
    max_s=a[i]
print(max_s)


77


15. List - Pair Sum Problem
Given a list of numbers and a target sum, find all pairs in the list that add up to the target.
Example:
Input: [2, 4, 3, 7, 1, 9], Target: 10
Output: [(3, 7), (1, 9)]


In [ ]:
input=[2,3,4,7,1,9,6]
target=10
temp=0
output=[]
for i in range(0,(len(input))):
  for j in range(i+1,len(input)):
    temp=input[i]+input[j]
    if(temp==target):
      output.append((input[i],input[j]))
print(output)

[(3, 7), (4, 6), (1, 9)]


Pandas & NumPy (5 Questions)
16. Pandas - Filtering DataFrame
You are given the following Pandas DataFrame:
import pandas as pd
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [24, 27, 22, 32],
    "Score": [85, 90, 78, 88]
})
Write a one-liner to filter and display only rows where Age is greater than 25.

In [ ]:
import pandas as pd
df = pd.DataFrame({"Name":["Alice","Bob","Charlie","David"],"Age":[24, 27, 22, 32],"Score":[85, 90, 78, 88]})
print(df[df['Age']>25])

    Name  Age  Score
1    Bob   27     90
3  David   32     88


17. Pandas - Group By Operation
You have the following DataFrame:
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [70000, 50000, 80000, 60000, 52000]
})
Write a Pandas command to calculate the average salary per department.

In [ ]:
df =pd.DataFrame({"Department": ["IT", "HR", "IT", "Finance", "HR"], "Salary":[70000, 50000, 80000, 60000, 52000],"age":[22,23,33,40,34]})
df.groupby('Department').mean()

Salary   age
Department               
Finance     60000.0  40.0
HR          51000.0  28.5
IT          75000.0  27.5

18. NumPy - Create a 5x5 Matrix
Write a program to create a 5x5 NumPy matrix where:
The diagonal elements are 1
All other elements are 0
Example:
Output:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
import numpy as np
print(np.identity(5,dtype=int))
print(np.ones((5,5),dtype=int))
print(np.zeros((5,5),dtype=int))
print(np.arange(25).reshape(5,5))
print(np.empty((5,5),dtype=int))


[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


19. NumPy - Element-wise Operations
Given two NumPy arrays:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
Perform element-wise:
Addition
Multiplication
Power (a^b)


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
print(a+b)
print(a-b)
print(a*b)
print(a**b)
print(a^b)

[11 22 33 44]
[ -9 -18 -27 -36]
[ 10  40  90 160]
[              1         1048576 205891132094649               0]
[11 22 29 44]


In [ ]:
4**40

1208925819614629174706176

20. NumPy - Find Index of Maximum Value
Given:
arr = np.array([10, 25, 39, 50, 19])
Write a one-liner to find the index of the maximum value.

In [ ]:
import numpy as np
arr=np.array([10, 25, 39, 50, 19])
arr.argmax()
#np.argmax(arr)

np.int64(3)