<a href="https://colab.research.google.com/github/Harish21b/sirpi/blob/main/Exe3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/contejhliuuhnt/drive')

Mounted at /content/drive


1. Loading a CSV File & Basic Exploration
Given a CSV file named "Automobile.csv":
Task
Write Python code to:
Load the CSV file into a Pandas DataFrame.
Display the first 30 rows.
Print column names.
Print No of Rows & Columns
Find the Data Types of every column & check if there are any mismatch
What are the minimum & maximum price of the car & state fuel type they belong to
List all the unique engine types
Find the horsepower range
What is the average mpg in cities & highway. Which is better?
What are the different Automobile makes present & which has maximum count?

In [ ]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/Data analytics /Automobile.csv')
print(df)

     symboling  normalized_losses         make fuel_type aspiration  \
0            3                168  alfa-romero       gas        std   
1            3                168  alfa-romero       gas        std   
2            1                168  alfa-romero       gas        std   
3            2                164         audi       gas        std   
4            2                164         audi       gas        std   
..         ...                ...          ...       ...        ...   
196         -1                 95        volvo       gas        std   
197         -1                 95        volvo       gas      turbo   
198         -1                 95        volvo       gas        std   
199         -1                 95        volvo    diesel      turbo   
200         -1                 95        volvo       gas      turbo   

    number_of_doors   body_style drive_wheels engine_location  wheel_base  \
0               two  convertible          rwd           front        8

In [ ]:
df.head()

symboling  normalized_losses         make fuel_type aspiration  \
0          3                168  alfa-romero       gas        std   
1          3                168  alfa-romero       gas        std   
2          1                168  alfa-romero       gas        std   
3          2                164         audi       gas        std   
4          2                164         audi       gas        std   

  number_of_doors   body_style drive_wheels engine_location  wheel_base  ...  \
0             two  convertible          rwd           front        88.6  ...   
1             two  convertible          rwd           front        88.6  ...   
2             two    hatchback          rwd           front        94.5  ...   
3            four        sedan          fwd           front        99.8  ...   
4            four        sedan          4wd           front        99.4  ...   

   engine_size  fuel_system  bore  stroke compression_ratio horsepower  \
0          130         mpfi  3.47    2.68               9.0        111   
1          130         mpfi  3.47    2.68               9.0        111   
2          152         mpfi  2.68    3.47               9.0        154   
3          109         mpfi  3.19    3.40              10.0        102   
4          136         mpfi  3.19    3.40               8.0        115   

   peak_rpm city_mpg  highway_mpg  price  
0      5000       21           27  13495  
1      5000       21           27  16500  
2      5000       19           26  16500  
3      5500       24           30  13950  
4      5500       18           22  17450  

[5 rows x 26 columns]

In [ ]:
print(df.head(30))

    symboling  normalized_losses         make fuel_type aspiration  \
0           3                168  alfa-romero       gas        std   
1           3                168  alfa-romero       gas        std   
2           1                168  alfa-romero       gas        std   
3           2                164         audi       gas        std   
4           2                164         audi       gas        std   
5           2                161         audi       gas        std   
6           1                158         audi       gas        std   
7           1                168         audi       gas        std   
8           1                158         audi       gas      turbo   
9           2                192          bmw       gas        std   
10          0                192          bmw       gas        std   
11          0                188          bmw       gas        std   
12          0                188          bmw       gas        std   
13          1       

In [ ]:
print(df.columns)

Index(['symboling', 'normalized_losses', 'make', 'fuel_type', 'aspiration',
       'number_of_doors', 'body_style', 'drive_wheels', 'engine_location',
       'wheel_base', 'length', 'width', 'height', 'curb_weight', 'engine_type',
       'number_of_cylinders', 'engine_size', 'fuel_system', 'bore', 'stroke',
       'compression_ratio', 'horsepower', 'peak_rpm', 'city_mpg',
       'highway_mpg', 'price'],
      dtype='object')


In [ ]:
print(df.shape)

(201, 26)


In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   symboling            201 non-null    int64  
 1   normalized_losses    201 non-null    int64  
 2   make                 201 non-null    object 
 3   fuel_type            201 non-null    object 
 4   aspiration           201 non-null    object 
 5   number_of_doors      201 non-null    object 
 6   body_style           201 non-null    object 
 7   drive_wheels         201 non-null    object 
 8   engine_location      201 non-null    object 
 9   wheel_base           201 non-null    float64
 10  length               201 non-null    float64
 11  width                201 non-null    float64
 12  height               201 non-null    float64
 13  curb_weight          201 non-null    int64  
 14  engine_type          201 non-null    object 
 15  number_of_cylinders  201 non-null    obj

What are the minimum & maximum price of the car & state fuel type they belong to

In [ ]:
min=df['price'].min()
df.loc[df['price']==min,("price","fuel_type")]

price fuel_type
134   5118       gas

In [ ]:
max=df['price'].max()
df.loc[df['price']==max,("price","fuel_type")]

price fuel_type
71  45400       gas

In [ ]:
df['engine_type'].unique()

array(['dohc', 'ohcv', 'ohc', 'l', 'rotor', 'ohcf'], dtype=object)

In [ ]:
df['horsepower'].min(),df['horsepower'].max()

(48, 262)

In [ ]:
ci=df['city_mpg'].mean()
hg=df['highway_mpg'].mean()
if(ci<hg):
    print(hg,"highway_mpg is better ")
else:
    print(ci,"city_mpg is better")

30.686567164179106 highway_mpg is better 


In [ ]:
df['make'].value_counts()


make
toyota           32
nissan           18
mazda            17
mitsubishi       13
honda            13
subaru           12
volkswagen       12
volvo            11
peugot           11
dodge             9
mercedes-benz     8
bmw               8
plymouth          7
audi              6
saab              6
porsche           4
chevrolet         3
alfa-romero       3
jaguar            3
isuzu             2
renault           2
mercury           1
Name: count, dtype: int64

2.Using the following DataFrame:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [24, 27, 22, 32],
    "Score": [85, 90, 78, 88
Task
Retrieve the row where Name == "Charlie" using .loc[].
Select only the Age and Score columns for "Alice" and "Bob" using .loc[].
]
})
88]


In [ ]:
import pandas as pd
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [24, 27, 22, 32],
    "Score": [85, 90, 78, 88]
})

print(df.loc[df['Name']=="Charlie",])
print(df.loc[df['Name'].isin(["Alice","Bob"]),"Age":"Score"])

      Name  Age  Score
2  Charlie   22     78
   Age  Score
0   24     85
1   27     90



3. Accessing Data with .iloc[]
Using the same DataFrame from Question 2, write code to:
Retrieve the second row using .iloc[].
Extract the last two rows using .iloc[].


In [ ]:
print(df.iloc[1:2,])
print(df.iloc[2:,])

  Name  Age  Score
1  Bob   27     90
      Name  Age  Score
2  Charlie   22     78
3    David   32     88


4. Filtering Rows Based on Conditions
Using the following DataFrame:
df = pd.DataFrame({
    "Employee": ["John", "Alice", "Bob", "David"],
    "Salary": [50000, 60000, 55000, 65000],
    "Department": ["IT", "HR", "IT", "Finance"]
})
Task
Write a Pandas command to:
Select only IT employees.
Select employees with a salary greater than 55,000

In [ ]:
import pandas as pd
df = pd.DataFrame({
    "Employee": ["John", "Alice", "Bob", "David"],
    "Salary": [50000, 60000, 55000, 65000],
    "Department": ["IT", "HR", "IT", "Finance"]
})

print(df.loc[df["Department"]=="IT","Employee":"Department"])

  Employee  Salary Department
0     John   50000         IT
2      Bob   55000         IT


In [ ]:
d=df.loc[df["Salary"]>=55000]
print(d)

  Employee  Salary Department
1    Alice   60000         HR
2      Bob   55000         IT
3    David   65000    Finance


5. Applying Functions to a Column
Using the following DataFrame:
df = pd.DataFrame({
    "Student": ["A", "B", "C", "D"],
    "Marks": [45, 78, 62, 90]
})
Task
Write a function that:
Converts marks below 50 to "Fail", and 50 or above to "Pass".
Apply this function to the "Marks" column and create a new column "Result".


In [ ]:
import pandas as pd
df=pd.DataFrame({
    "Student":["A","B","c","d"],
    "Marks":[45,78,62,90]
})
def mark(marks):
    return "pass" if marks>=50 else "fail"
df["result"]=df["Marks"].apply(mark)
print(df)

  Student  Marks result
0       A     45   fail
1       B     78   pass
2       c     62   pass
3       d     90   pass


6. NumPy - Creating and Reshaping Arrays
Write Python code to:
Create a NumPy array with values from 1 to 12.
Reshape it into a 3x4 matrix.


In [ ]:
import numpy as np
print(np.arange(1,13).reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


7. NumPy - Broadcasting & Element-wise Operations
You are given the following NumPy arrays:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
Task
Perform:
Element-wise multiplication of a and b.
Add 5 to each element of a using broadcasting.


In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print(a,b)
print("multiplication",a*b)
a=a+5
b=b+5
print("after additon",a,b)


[1 2 3] [10 20 30]
multiplication [10 40 90]
after additon [6 7 8] [15 25 35]


8. Finding Maximum and Minimum Values in a NumPy Array
Given:
arr = np.array([[3, 7, 2], [4, 9, 6]])
Task
Find the maximum value in the entire array.
Find the minimum value in each row

In [ ]:
a=(np.array([[3, 7, 2], [4, 9, 6]]))
print(a)
print(np.min(a,axis=0))#ie to mention column axis=0
print(np.min(a,axis=1))#ie to mention rows axis=1

[[3 7 2]
 [4 9 6]]
[3 7 2]
[2 4]


9. Grouping & Aggregation in Pandas
You have the following DataFrame:
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [70000, 50000, 80000, 60000, 52000]
})
Task
Write a Pandas command to:
Group the DataFrame by "Department" and calculate the average salary per department.


In [ ]:
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [70000, 50000, 80000, 60000, 52000]
})
print(df.groupby('Department')['Salary'].mean())

Department
Finance    60000.0
HR         51000.0
IT         75000.0
Name: Salary, dtype: float64


10. Sorting a DataFrame
Given the following DataFrame:
df = pd.DataFrame({
    "City": ["New York", "Los Angeles", "Chicago", "Houston"],
    "Population": [8419600, 3980400, 2716000, 2328000]
})
Task
Sort the DataFrame by Population in descending order.


In [ ]:
df = pd.DataFrame({
    "City": ["New York", "Los Angeles", "Chicago", "Houston"],
    "Population": [8419600, 3980400, 2716000, 2328000]
})

df.sort_values('Population',ascending=False)

City  Population
0     New York     8419600
1  Los Angeles     3980400
2      Chicago     2716000
3      Houston     2328000

11. Multi-Indexing in Pandas
You are given the following DataFrame:
data = {
    "Region": ["North", "North", "South", "South", "East", "East"],
    "City": ["A", "B", "A", "B", "A", "B"],
    "Sales": [200, 150, 180, 220, 300, 250]
}
df = pd.DataFrame(data).set_index(["Region", "City"])
Task
Retrieve the sales value for City A in the South Region using multi-indexing.

In [ ]:
import pandas as pd
data = {
    "Region": ["North", "North", "South", "South", "East", "East"],
    "City": ["A", "B", "A", "B", "A", "B"],
    "Sales": [200, 150, 180, 220, 300, 250]
}
df=pd.DataFrame(data).set_index(["Region","City"])
print(df)
print(df.loc[("South","A")])

             Sales
Region City       
North  A       200
       B       150
South  A       180
       B       220
East   A       300
       B       250
             Sales
Region City       
North  A       200
       B       150
South  A       180
       B       220
East   A       300
       B       250
Sales    180
Name: (South, A), dtype: int64


12. Creating a DataFrame from a NumPy Array
Generate a 5x4 NumPy array with random integers between 10 and 99 and convert it into a Pandas DataFrame with column names ["A", "B", "C", "D"].

In [ ]:
import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randint(10,99,size=(5,4)),columns=["A","B","C","D"])
print(df)

    A   B   C   D
0  81  35  43  72
1  49  95  74  20
2  57  10  71  85
3  72  83  61  44
4  18  94  87  56


13. Conditional Column Update
Given the following DataFrame:
df = pd.DataFrame({
    "Student": ["Alice", "Bob", "Charlie", "David"],
    "Marks": [88, 45, 76, 90],
    "Attendance": [85, 50, 90, 60]
})
 Task
Write a one-liner Pandas command to set "Marks" to 0 for students whose "Attendance" is less than 60.

In [ ]:
df=pd.DataFrame({ "Student": ["Alice", "Bob", "Charlie", "David"], "Marks": [88, 45, 76, 90], "Attendance": [85, 50, 90, 60] })
df.loc[df["Attendance"]<60,"Marks"]=0
print(df)

   Student  Marks  Attendance
0    Alice     88          85
1      Bob      0          50
2  Charlie     76          90
3    David     90          60


14. Advanced Filtering
From a CSV file "employees.csv" with columns:
EmployeeID, Department, Salary, Experience (in years).
Note: You should create “employees.csv” & perform the below task
Task
Write a Pandas query to:
Select employees from "IT" or "Finance" department
Having Salary > 60,000
AND at least 5 years of experience

In [ ]:
import pandas as pd
data = {
    "EmployeeID": [1, 2, 3, 4, 5, 6, 7],
    "Department": ["IT", "HR", "Finance", "IT", "HR", "Finance", "IT"],
    "Salary": [70000, 62000, 65000, 80000, 50000, 75000, 62000],
    "Experience": [6, 4, 5, 7, 3, 8, 5]
}
df=pd.DataFrame(data)
df.to_csv("harish.csv")

df=pd.read_csv("harish.csv")
a=df[(df["Department"].isin(["IT","Finance"]))&(df["Salary"]>60000)&(df["Experience"]>=5)]
print(a)



   Unnamed: 0  EmployeeID Department  Salary  Experience
0           0           1         IT   70000           6
2           2           3    Finance   65000           5
3           3           4         IT   80000           7
5           5           6    Finance   75000           8
6           6           7         IT   62000           5


15. Grouping & Aggregation with Multiple Conditions
Given the following DataFrame:
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance", "IT"],
    "Salary": [70000, 50000, 80000, 60000, 52000, 72000, 65000],
    "Experience": [5, 4, 7, 3, 2, 8, 6]
})
Task
Find the average salary for each department, but only for employees with at least 5 years of experience.

In [ ]:
df=pd.DataFrame({"Department": ["IT", "HR", "IT", "Finance", "HR", "Finance", "IT"],
                   "Salary": [70000, 50000, 80000, 60000, 52000, 72000, 65000],
                   "Experience": [5, 4, 7, 3, 2, 8, 6] })
a=df["Experience"]>=5
b=df[a].groupby("Department")["Salary"].mean()
print(b)

Department
Finance    72000.000000
IT         71666.666667
Name: Salary, dtype: float64


16. NumPy - Complex Indexing
Create a 5x5 NumPy array with random values between 1 and 100.
Write a NumPy command to:
Extract only even numbers from the array.
Extract values from the last row and last column.
Replace all values greater than 50 with 0.

In [ ]:
import numpy as np
mat1=np.random.randint(1,101,size=(5,5))
print("Random 5*5matrix:",mat1,sep="\n")
mat2=mat1[mat1 % 2 ==0]
print("The even numbers in the matrix:",mat2)

a=(mat1[-1,])
print("The last row in the matrix :",a)
b=(mat1[:,-1])
print("The last column in the matrix :",b)
mat1[mat1 > 50]=0
print("After changing the values greater the 50 to 0 :",mat1,sep="\n")

Random 5*5matrix:
[[75 54 40 70 56]
 [10 41 74 75 57]
 [94 72 72 23 45]
 [16 80 67 37 58]
 [49 78 58 45 23]]
The even numbers in the matrix: [54 40 70 56 10 74 94 72 72 16 80 58 78 58]
The last row in the matrix : [49 78 58 45 23]
The last column in the matrix : [56 57 45 58 23]
After changing the values greater the 50 to 0 :
[[ 0  0 40  0  0]
 [10 41  0  0  0]
 [ 0  0  0 23 45]
 [16  0  0 37  0]
 [49  0  0 45 23]]


17. Matrix Multiplication
Given the two NumPy matrices:
A = np.array([[2, 4], [6, 8]])
B = np.array([[1, 3], [5, 7]])
Task
Perform matrix multiplication and output the result.


In [ ]:
A = np.array([[2, 4], [6, 8]])
B = np.array([[1, 3], [5, 7]])
c=A*B
print(c)

[[ 2 12]
 [30 56]]


18. Finding Unique & Common Elements
You are given two NumPy arrays:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([30, 40, 70, 80, 90])
Task
Find the elements that are common in both arrays.
Find the elements that are only present in arr1 but not in arr2.

In [ ]:
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([30, 40, 70, 80, 90])
print(np.intersect1d(arr1,arr2))
print(np.setdiff1d(arr1,arr2))


[30 40]
[10 20 50 60]


19. Sorting & Ranking in Pandas
You are given the following DataFrame:
df = pd.DataFrame({
    "Player": ["A", "B", "C", "D"],
    "Score": [200, 450, 300, 150]
})
Task
Sort the players by descending Score.
Assign ranking to each player (1st, 2nd, 3rd...) without skipping numbers.

In [ ]:
import pandas as pd
df=pd.DataFrame({ "Player": ["A", "B", "C", "D"],"Score": [200, 450, 300, 150] })
df_sorted=df.sort_values("Score",ascending=False)
df_sorted["Rank"]=df_sorted["Score"].rank(ascending=False).astype(int)
print(df_sorted)


  Player  Score  Rank
1      B    450     1
2      C    300     2
0      A    200     3
3      D    150     4


20. Optimizing Pandas Performance
You have a large CSV file ("big_data.csv") with 1 million rows.
Note: You should search & download a large csv file from any portal & use it to perform below tasks
Task
Write optimized Pandas code to:
Load only specific columns: "CustomerID" and "PurchaseAmount".
Load only the first 100,000 rows.
Use an efficient data type for "CustomerID" to save memory.